<?php

error_reporting(E_ALL);
ini_set('display_errors', '1');

echo '<h1>AJSMR INCLUDE DIAGNOSTIC</h1>';

$files = [
    'socialicons.php',
    'authorsearch.php',
    'search.php',
    'footer.php'
];

foreach ($files as $file) {

    echo '<hr>';
    echo '<h2>Testing: ' . htmlspecialchars($file) . '</h2>';

    if (!file_exists(__DIR__ . '/' . $file)) {

        echo '<p style="color:red;"><strong>FILE NOT FOUND</strong></p>';
        continue;
    }

    echo '<p>File exists.</p>';

    ob_start();

    try {

        include __DIR__ . '/' . $file;

        $output = ob_get_clean();

        echo '<p style="color:green;"><strong>INCLUDE SUCCESSFUL</strong></p>';

        if ($output !== '') {
            echo '<details>';
            echo '<summary>Output generated by file</summary>';
            echo '<div style="border:1px solid #ccc;padding:10px;margin-top:10px;">';
            echo $output;
            echo '</div>';
            echo '</details>';
        }

    } catch (Throwable $e) {

        ob_end_clean();

        echo '<p style="color:red;"><strong>INCLUDE FAILED</strong></p>';

        echo '<pre style="background:#f5f5f5;padding:10px;">';
        echo htmlspecialchars(
            get_class($e) . ': ' . $e->getMessage()
        );
        echo "\n\nFile: " .
             htmlspecialchars($e->getFile());
        echo "\nLine: " .
             htmlspecialchars((string)$e->getLine());
        echo '</pre>';
    }
}

echo '<hr>';
echo '<h2>Diagnostic completed.</h2>';

?>