-- AJSMR Phase 1 complete 16-section submission system
-- Preserves legacy submitmanuscripts table.

CREATE TABLE IF NOT EXISTS ajsmr_submissions (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 manuscript_no VARCHAR(32) NOT NULL,
 article_type VARCHAR(100) NOT NULL,
 title TEXT NOT NULL,
 running_title VARCHAR(500),
 abstract_text LONGTEXT NOT NULL,
 keywords TEXT,
 word_count INT UNSIGNED,
 figure_count INT UNSIGNED,
 table_count INT UNSIGNED,
 corresponding_name VARCHAR(255) NOT NULL,
 corresponding_email VARCHAR(255) NOT NULL,
 corresponding_orcid VARCHAR(50),
 corresponding_institution VARCHAR(500) NOT NULL,
 corresponding_department VARCHAR(255),
 corresponding_city VARCHAR(150),
 corresponding_state VARCHAR(150),
 corresponding_country VARCHAR(150) NOT NULL,
 corresponding_postal_code VARCHAR(30),
 corresponding_phone VARCHAR(50),
 funding_status VARCHAR(20) NOT NULL DEFAULT 'none',
 funding_statement TEXT,
 conflict_status VARCHAR(20) NOT NULL DEFAULT 'none',
 conflict_statement TEXT,
 ethics_status VARCHAR(30) NOT NULL DEFAULT 'not_applicable',
 ethics_statement TEXT,
 ethics_committee VARCHAR(500),
 ethics_approval_no VARCHAR(255),
 ethics_approval_date VARCHAR(50),
 consent_status VARCHAR(30) NOT NULL DEFAULT 'not_applicable',
 trial_registry VARCHAR(255),
 trial_number VARCHAR(255),
 trial_date VARCHAR(50),
 data_status VARCHAR(30) NOT NULL DEFAULT 'not_applicable',
 data_repository VARCHAR(500),
 data_identifier VARCHAR(500),
 ai_status VARCHAR(10) NOT NULL DEFAULT 'no',
 ai_statement TEXT,
 originality_confirmed TINYINT(1) NOT NULL DEFAULT 0,
 authors_approved TINYINT(1) NOT NULL DEFAULT 0,
 exclusive_submission_confirmed TINYINT(1) NOT NULL DEFAULT 0,
 accuracy_confirmed TINYINT(1) NOT NULL DEFAULT 0,
 permissions_confirmed TINYINT(1) NOT NULL DEFAULT 0,
 privacy_confirmed TINYINT(1) NOT NULL DEFAULT 0,
 status VARCHAR(40) NOT NULL DEFAULT 'submitted',
 submitted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 ip_hash CHAR(64),
 user_agent_hash CHAR(64),
 PRIMARY KEY(id),
 UNIQUE KEY uq_manuscript_no(manuscript_no),
 KEY idx_email(corresponding_email),
 KEY idx_status(status),
 KEY idx_submitted_at(submitted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ajsmr_submission_authors (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 submission_id BIGINT UNSIGNED NOT NULL,
 author_order INT UNSIGNED NOT NULL,
 given_name VARCHAR(150) NOT NULL,
 middle_name VARCHAR(150),
 family_name VARCHAR(150) NOT NULL,
 email VARCHAR(255),
 orcid VARCHAR(50),
 department VARCHAR(255),
 institution VARCHAR(500) NOT NULL,
 city VARCHAR(150),
 state VARCHAR(150),
 country VARCHAR(150) NOT NULL,
 contribution TEXT,
 is_corresponding TINYINT(1) NOT NULL DEFAULT 0,
 PRIMARY KEY(id), KEY idx_submission(submission_id),
 CONSTRAINT fk_asa FOREIGN KEY(submission_id) REFERENCES ajsmr_submissions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ajsmr_submission_affiliations (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 submission_id BIGINT UNSIGNED NOT NULL,
 affiliation_no INT UNSIGNED NOT NULL,
 department VARCHAR(500),
 institution VARCHAR(500) NOT NULL,
 city VARCHAR(150),
 state VARCHAR(150),
 country VARCHAR(150) NOT NULL,
 PRIMARY KEY(id), KEY idx_submission(submission_id),
 CONSTRAINT fk_aff FOREIGN KEY(submission_id) REFERENCES ajsmr_submissions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ajsmr_submission_reviewers (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 submission_id BIGINT UNSIGNED NOT NULL,
 reviewer_type VARCHAR(20) NOT NULL,
 full_name VARCHAR(255) NOT NULL,
 institution VARCHAR(500),
 country VARCHAR(150),
 email VARCHAR(255),
 orcid VARCHAR(50),
 expertise VARCHAR(1000),
 exclusion_reason VARCHAR(1000),
 PRIMARY KEY(id), KEY idx_submission(submission_id),
 CONSTRAINT fk_rev FOREIGN KEY(submission_id) REFERENCES ajsmr_submissions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ajsmr_submission_files (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 submission_id BIGINT UNSIGNED NOT NULL,
 file_type VARCHAR(60) NOT NULL,
 original_name VARCHAR(255) NOT NULL,
 stored_name VARCHAR(255) NOT NULL,
 relative_path VARCHAR(500) NOT NULL,
 mime_type VARCHAR(150) NOT NULL,
 file_size BIGINT UNSIGNED NOT NULL,
 sha256 CHAR(64) NOT NULL,
 uploaded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(id), KEY idx_submission(submission_id),
 CONSTRAINT fk_files FOREIGN KEY(submission_id) REFERENCES ajsmr_submissions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
