<?php
declare(strict_types=1);
session_start();
require_once __DIR__.'/ajsmr_submission_config.php';

$types=['Original Research','Review Article','Short Communication','Case Report','Case Series','Editorial','Letter to the Editor','Methodology/Technical Article','Other'];
$contrib=['Conceptualization','Methodology','Software','Validation','Formal analysis','Investigation','Resources','Data curation','Writing – original draft','Writing – review & editing','Visualization','Supervision','Project administration','Funding acquisition'];
$errors=[];$old=$_POST;
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  check_csrf((string)($_POST['csrf']??''));
  $type=trim((string)($_POST['article_type']??''));$title=trim((string)($_POST['title']??''));$abstract=trim((string)($_POST['abstract']??''));
  $cn=trim((string)($_POST['corresponding_name']??''));$ce=strtolower(trim((string)($_POST['corresponding_email']??'')));$ci=trim((string)($_POST['corresponding_institution']??''));$cc=trim((string)($_POST['corresponding_country']??''));
  if(!in_array($type,$types,true))$errors[]='Select a valid article type.';
  if(mb_strlen($title)<10)$errors[]='Full manuscript title is required.';
  if(mb_strlen($abstract)<50)$errors[]='Abstract must contain at least 50 characters.';
  if($cn==='')$errors[]='Corresponding author name is required.';
  if(!filter_var($ce,FILTER_VALIDATE_EMAIL))$errors[]='Valid corresponding-author email is required.';
  if($ci==='')$errors[]='Corresponding author institution is required.';
  if($cc==='')$errors[]='Corresponding author country is required.';
  if(!orcid_ok(trim((string)($_POST['corresponding_orcid']??''))))$errors[]='Invalid corresponding-author ORCID format.';
  $authors=$_POST['authors']??[];$affs=$_POST['affiliations']??[];
  if(!is_array($authors)||count($authors)<1)$errors[]='At least one author is required.';
  foreach((array)$authors as $a){if(!is_array($a)||trim((string)($a['given_name']??''))===''||trim((string)($a['family_name']??''))===''||trim((string)($a['institution']??''))===''||trim((string)($a['country']??''))==='')$errors[]='Each author needs given name, family name, institution and country.';if(!orcid_ok(trim((string)($a['orcid']??''))))$errors[]='One author has an invalid ORCID format.';}
  $main=$_FILES['main_manuscript']??null;if(!$main||(int)$main['error']!==UPLOAD_ERR_OK)$errors[]='Main manuscript is required.';
  foreach(['originality_confirmed'=>'Originality confirmation is required.','authors_approved'=>'All-author approval is required.','exclusive_submission_confirmed'=>'Exclusive-submission confirmation is required.','accuracy_confirmed'=>'Accuracy/integrity confirmation is required.','permissions_confirmed'=>'Permissions confirmation is required.','privacy_confirmed'=>'Privacy acceptance is required.'] as $k=>$m)if(empty($_POST[$k]))$errors[]=$m;
  if(!$errors){
   $pdo=ajsmr_db();$pdo->beginTransaction();$no=manuscript_no($pdo);$ch=client_hashes();
   $valid=['funding_status'=>['none','funded'],'conflict_status'=>['none','yes'],'ethics_status'=>['not_applicable','required','approved','not_required'],'consent_status'=>['not_applicable','obtained','not_required'],'data_status'=>['not_applicable','repository','request','included','cannot_share'],'ai_status'=>['no','yes']];
   foreach($valid as $k=>$opts)if(!in_array($_POST[$k]??'',$opts,true))$_POST[$k]=$opts[0];
   $submissionColumns = [
    'manuscript_no','article_type','title','running_title','abstract_text','keywords',
    'word_count','figure_count','table_count','corresponding_name','corresponding_email',
    'corresponding_orcid','corresponding_institution','corresponding_department',
    'corresponding_city','corresponding_state','corresponding_country',
    'corresponding_postal_code','corresponding_phone','funding_status','funding_statement',
    'conflict_status','conflict_statement','ethics_status','ethics_statement',
    'ethics_committee','ethics_approval_no','ethics_approval_date','consent_status',
    'trial_registry','trial_number','trial_date','data_status','data_repository',
    'data_identifier','ai_status','ai_statement','originality_confirmed','authors_approved',
    'exclusive_submission_confirmed','accuracy_confirmed','permissions_confirmed',
    'privacy_confirmed','status','ip_hash','user_agent_hash'
];
$q=$pdo->prepare(
    'INSERT INTO ajsmr_submissions (' . implode(',', $submissionColumns) . ') VALUES (' .
    implode(',', array_fill(0,count($submissionColumns),'?')) . ')'
);
   $q->execute([$no,$type,$title,trim((string)($_POST['running_title']??'')),$abstract,trim((string)($_POST['keywords']??'')),($_POST['word_count']??'')===''?null:(int)$_POST['word_count'],($_POST['figure_count']??'')===''?null:(int)$_POST['figure_count'],($_POST['table_count']??'')===''?null:(int)$_POST['table_count'],$cn,$ce,trim((string)($_POST['corresponding_orcid']??'')),$ci,trim((string)($_POST['corresponding_department']??'')),trim((string)($_POST['corresponding_city']??'')),trim((string)($_POST['corresponding_state']??'')),$cc,trim((string)($_POST['corresponding_postal_code']??'')),trim((string)($_POST['corresponding_phone']??'')),$_POST['funding_status'],trim((string)($_POST['funding_statement']??'')),$_POST['conflict_status'],trim((string)($_POST['conflict_statement']??'')),$_POST['ethics_status'],trim((string)($_POST['ethics_statement']??'')),trim((string)($_POST['ethics_committee']??'')),trim((string)($_POST['ethics_approval_no']??'')),trim((string)($_POST['ethics_approval_date']??'')),$_POST['consent_status'],trim((string)($_POST['trial_registry']??'')),trim((string)($_POST['trial_number']??'')),trim((string)($_POST['trial_date']??'')),$_POST['data_status'],trim((string)($_POST['data_repository']??'')),trim((string)($_POST['data_identifier']??'')),$_POST['ai_status'],trim((string)($_POST['ai_statement']??'')),1,1,1,1,1,1,'submitted',$ch['ip_hash'],$ch['user_agent_hash']]);
   $sid=(int)$pdo->lastInsertId();
   $qa=$pdo->prepare('INSERT INTO ajsmr_submission_authors(submission_id,author_order,given_name,middle_name,family_name,email,orcid,department,institution,city,state,country,contribution,is_corresponding) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
   foreach($authors as $i=>$a){$c=$a['contribution']??[];$qa->execute([$sid,$i+1,trim((string)$a['given_name']),trim((string)($a['middle_name']??'')),trim((string)$a['family_name']),strtolower(trim((string)($a['email']??''))),trim((string)($a['orcid']??'')),trim((string)($a['department']??'')),trim((string)$a['institution']),trim((string)($a['city']??'')),trim((string)($a['state']??'')),trim((string)$a['country']),is_array($c)?implode('; ',array_map('trim',$c)):trim((string)$c),$i===0?1:0]);}
   $qf=$pdo->prepare('INSERT INTO ajsmr_submission_affiliations(submission_id,affiliation_no,department,institution,city,state,country) VALUES(?,?,?,?,?,?,?)');
   foreach((array)$affs as $i=>$a)if(is_array($a)&&trim((string)($a['institution']??''))!=='')$qf->execute([$sid,$i+1,trim((string)($a['department']??'')),trim((string)$a['institution']),trim((string)($a['city']??'')),trim((string)($a['state']??'')),trim((string)($a['country']??''))]);
   $qr=$pdo->prepare('INSERT INTO ajsmr_submission_reviewers(submission_id,reviewer_type,full_name,institution,country,email,orcid,expertise,exclusion_reason) VALUES(?,?,?,?,?,?,?,?,?)');
   foreach(['suggested','excluded'] as $rt)foreach((array)($_POST[$rt.'_reviewers']??[]) as $r)if(is_array($r)&&trim((string)($r['full_name']??''))!=='')$qr->execute([$sid,$rt,trim((string)$r['full_name']),trim((string)($r['institution']??'')),trim((string)($r['country']??'')),strtolower(trim((string)($r['email']??''))),trim((string)($r['orcid']??'')),trim((string)($r['expertise']??'')),trim((string)($r['reason']??''))]);
   $dir=__DIR__.'/submissiondocs/'.$no;if(!is_dir($dir)&&!mkdir($dir,0750,true))throw new RuntimeException('Cannot create submission storage directory.');
   $allowed=['main_manuscript'=>['doc','docx','pdf'],'title_page'=>['doc','docx','pdf'],'cover_letter'=>['doc','docx','pdf','txt'],'copyright_form'=>['pdf','jpg','jpeg','png'],'ethics_document'=>['pdf','jpg','jpeg','png'],'figures'=>['pdf','jpg','jpeg','png','tif','tiff'],'tables'=>['doc','docx','pdf','xls','xlsx','csv'],'supplementary'=>['doc','docx','pdf','xls','xlsx','csv','zip']];
   $qfile=$pdo->prepare('INSERT INTO ajsmr_submission_files(submission_id,file_type,original_name,stored_name,relative_path,mime_type,file_size,sha256) VALUES(?,?,?,?,?,?,?,?)');$fi=new finfo(FILEINFO_MIME_TYPE);
   foreach($allowed as $field=>$exts){$arr=$_FILES[$field]??null;if(!$arr)continue;$items=isset($arr['name'])&&is_array($arr['name'])?array_map(null,$arr['name'],$arr['type'],$arr['tmp_name'],$arr['error'],$arr['size']):[$arr];foreach($items as $item){if(isset($item['error'])){$name=$item['name'];$tmp=$item['tmp_name'];$err=$item['error'];$size=$item['size'];}else{[$name,$mime0,$tmp,$err,$size]=$item;}if((int)$err===UPLOAD_ERR_NO_FILE)continue;if((int)$err!==UPLOAD_ERR_OK)throw new RuntimeException("Upload failed for $field.");if((int)$size>20*1024*1024)throw new RuntimeException("A file in $field exceeds 20 MB.");$ext=strtolower(pathinfo((string)$name,PATHINFO_EXTENSION));if(!in_array($ext,$exts,true))throw new RuntimeException("File type is not permitted for $field.");$mime=$fi->file((string)$tmp)?:'application/octet-stream';$stored=bin2hex(random_bytes(18)).'.'.$ext;$dest=$dir.'/'.$stored;if(!move_uploaded_file((string)$tmp,$dest))throw new RuntimeException("Could not store $field.");$qfile->execute([$sid,$field,basename((string)$name),$stored,'submissiondocs/'.$no.'/'.$stored,$mime,(int)$size,hash_file('sha256',$dest)]);}}
   $pdo->commit();header('Location: submission-success.php?no='.rawurlencode($no));exit;
  }
 }catch(Throwable $e){if(isset($pdo)&&$pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();$errors[]='Submission could not be completed: '.$e->getMessage();}
}
$token=csrf();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AJSMR — Submit Manuscript</title><link rel="stylesheet" href="ajsmr-submission.css"></head><body><div class="wrap">
<div class="hero"><h1>AJSMR Manuscript Submission</h1><p>Complete all 16 sections. Required fields are marked <span class="req">*</span>. This local-testing version does not modify the legacy <code>submitmanuscripts</code> table.</p></div>
<div class="stepbar"><?php for($i=1;$i<=16;$i++):?><span class="step <?= $i===1?'active':''?>"><?=$i?></span><?php endfor;?></div>
<?php if($errors):?><div class="error"><strong>Please correct the following:</strong><ul><?php foreach($errors as $e):?><li><?=h($e)?></li><?php endforeach;?></ul></div><?php endif;?>
<form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=h($token)?>">

<section class="card"><h2>1. Manuscript Type</h2><div class="field"><label>Article Type <span class="req">*</span></label><select name="article_type" required><option value="">Select</option><?php foreach($types as $v):?><option><?=h($v)?></option><?php endforeach;?></select></div></section>

<section class="card"><h2>2. Manuscript Information</h2><div class="grid"><div class="field"><label>Full Title <span class="req">*</span></label><input class="full" name="title" required></div><div class="field"><label>Running Title</label><input name="running_title"></div><div class="field full"><label>Abstract <span class="req">*</span></label><textarea name="abstract" required></textarea></div><div class="field full"><label>Keywords</label><input name="keywords" placeholder="Separate by commas"></div></div><div class="grid3"><div class="field"><label>Word Count</label><input type="number" min="0" name="word_count"></div><div class="field"><label>Figure Count</label><input type="number" min="0" name="figure_count"></div><div class="field"><label>Table Count</label><input type="number" min="0" name="table_count"></div></div></section>

<section class="card"><h2>3. Corresponding Author</h2><div class="grid"><?php foreach([['corresponding_name','Full Name *'],['corresponding_email','Email *'],['corresponding_orcid','ORCID'],['corresponding_institution','Institution *'],['corresponding_department','Department'],['corresponding_city','City'],['corresponding_state','State/Province'],['corresponding_country','Country *'],['corresponding_postal_code','Postal Code'],['corresponding_phone','Telephone']] as $f):?><div class="field"><label><?=h($f[1])?></label><input <?=str_contains($f[1],'Email')?'type="email"':''?> name="<?=h($f[0])?>" <?=str_contains($f[1],'*')?'required':''?>></div><?php endforeach;?></div></section>

<section class="card"><h2>4. All Authors</h2><div id="authors"></div><button type="button" class="btn alt" onclick="addAuthor()">+ Add Author</button></section>

<section class="card"><h2>5. Author Affiliations</h2><p class="small">Enter the distinct affiliations used by the authors.</p><div id="affs"></div><button type="button" class="btn alt" onclick="addAff()">+ Add Affiliation</button></section>

<section class="card"><h2>6. Author Contributions</h2><p class="small">Contribution roles are captured within each author record using CRediT-style categories. Select all roles applicable to each author.</p></section>

<section class="card"><h2>7. Funding Information</h2><div class="grid"><div class="field"><label>Funding Status</label><select name="funding_status"><option value="none">No external funding</option><option value="funded">Funded</option></select></div><div class="field full"><label>Funding Statement</label><textarea name="funding_statement"></textarea></div></div></section>

<section class="card"><h2>8. Conflict of Interest</h2><div class="grid"><div class="field"><label>Conflict Status</label><select name="conflict_status"><option value="none">No conflicts to declare</option><option value="yes">Conflict exists / disclose below</option></select></div><div class="field full"><label>Conflict Statement</label><textarea name="conflict_statement"></textarea></div></div></section>

<section class="card"><h2>9. Research Ethics & Consent</h2><div class="grid"><div class="field"><label>Ethics Status</label><select name="ethics_status"><option value="not_applicable">Not applicable</option><option value="required">Required</option><option value="approved">Approved</option><option value="not_required">Not required</option></select></div><div class="field"><label>Consent Status</label><select name="consent_status"><option value="not_applicable">Not applicable</option><option value="obtained">Obtained</option><option value="not_required">Not required</option></select></div><div class="field"><label>Ethics Committee</label><input name="ethics_committee"></div><div class="field"><label>Approval Number</label><input name="ethics_approval_no"></div><div class="field"><label>Approval Date</label><input name="ethics_approval_date"></div><div class="field full"><label>Ethics / Consent Statement</label><textarea name="ethics_statement"></textarea></div></div></section>

<section class="card"><h2>10. Clinical Trial Registration</h2><div class="grid"><div class="field"><label>Registry</label><input name="trial_registry"></div><div class="field"><label>Registration Number</label><input name="trial_number"></div><div class="field"><label>Registration Date</label><input name="trial_date"></div></div></section>

<section class="card"><h2>11. Data Availability</h2><div class="grid"><div class="field"><label>Data Availability</label><select name="data_status"><option value="not_applicable">Not applicable</option><option value="repository">Public repository</option><option value="request">Available on reasonable request</option><option value="included">Included in article/supplement</option><option value="cannot_share">Cannot be shared; explanation required</option></select></div><div class="field"><label>Repository</label><input name="data_repository"></div><div class="field full"><label>Dataset DOI / URL / Identifier</label><input name="data_identifier"></div></div></section>

<section class="card"><h2>12. AI / Generative AI Disclosure</h2><div class="field"><label>Was generative AI used?</label><select name="ai_status"><option value="no">No</option><option value="yes">Yes</option></select></div><div class="field"><label>If yes, disclose tool/version, purpose and where used</label><textarea name="ai_statement"></textarea></div><div class="reviewbox">AI tools cannot be listed as authors. Authors remain responsible for the submitted work.</div></section>

<section class="card"><h2>13. Reviewer Information</h2><p class="small">Suggestions are advisory; editors independently assess suitability and conflicts.</p><div id="reviewers"></div><button type="button" class="btn alt" onclick="addReviewer('suggested')">+ Suggested Reviewer</button> <button type="button" class="btn alt" onclick="addReviewer('excluded')">+ Reviewer to Exclude</button></section>

<section class="card"><h2>14. Manuscript Files</h2><div class="grid"><div class="field full"><label>Main Manuscript <span class="req">*</span></label><input type="file" name="main_manuscript" required accept=".doc,.docx,.pdf"></div><div class="field"><label>Separate Title Page</label><input type="file" name="title_page" accept=".doc,.docx,.pdf"></div><div class="field"><label>Cover Letter</label><input type="file" name="cover_letter" accept=".doc,.docx,.pdf,.txt"></div><div class="field"><label>Copyright / License Form</label><input type="file" name="copyright_form" accept=".pdf,.jpg,.jpeg,.png"></div><div class="field"><label>Ethics Approval Document</label><input type="file" name="ethics_document" accept=".pdf,.jpg,.jpeg,.png"></div><div class="field"><label>Figures</label><input type="file" name="figures[]" multiple accept=".pdf,.jpg,.jpeg,.png,.tif,.tiff"></div><div class="field"><label>Tables</label><input type="file" name="tables[]" multiple accept=".doc,.docx,.pdf,.xls,.xlsx,.csv"></div><div class="field full"><label>Supplementary Material</label><input type="file" name="supplementary[]" multiple accept=".doc,.docx,.pdf,.xls,.xlsx,.csv,.zip"></div></div><p class="small">Maximum 20 MB per file. Executable files are prohibited. Files are stored using randomized server-side names.</p></section>

<section class="card"><h2>15. Declarations & Author Agreement</h2><?php foreach(['originality_confirmed'=>'The manuscript is original and has not been published previously in the submitted form.','authors_approved'=>'All listed authors have approved the manuscript and agree with its submission to AJSMR.','exclusive_submission_confirmed'=>'The manuscript is not simultaneously under consideration by another journal.','accuracy_confirmed'=>'The authors accept responsibility for the accuracy, integrity and proper citation of the work.','permissions_confirmed'=>'All required permissions for third-party copyrighted material have been obtained.','privacy_confirmed'=>'I accept AJSMR processing the submitted personal data for editorial and publication purposes according to the journal privacy policy.'] as $k=>$v):?><label class="check"><input type="checkbox" name="<?=$k?>" value="1" required><span><?=h($v)?> <span class="req">*</span></span></label><?php endforeach;?></section>

<section class="card"><h2>16. Review & Final Submission</h2><div class="reviewbox"><strong>Before clicking Submit Manuscript:</strong><br>Review the title, authors, affiliations, declarations and files. The system will generate a unique AJSMR manuscript number after successful database and file validation.</div><br><div class="actions"><button type="submit" class="btn">Submit Manuscript</button><button type="reset" class="btn red">Reset Form</button></div></section>
</form></div>
<script>
const C=<?=json_encode($contrib,JSON_UNESCAPED_UNICODE)?>;let ac=0,af=0,rc=0;
function addAuthor(){let i=ac++,d=document.createElement('div');d.className='author';d.innerHTML=`<h3>Author ${i+1}</h3><div class="grid"><div class="field"><label>Given Name *</label><input name="authors[${i}][given_name]" required></div><div class="field"><label>Middle Name</label><input name="authors[${i}][middle_name]"></div><div class="field"><label>Family Name *</label><input name="authors[${i}][family_name]" required></div><div class="field"><label>Email</label><input type="email" name="authors[${i}][email]"></div><div class="field"><label>ORCID</label><input name="authors[${i}][orcid]" placeholder="0000-0000-0000-0000"></div><div class="field"><label>Department</label><input name="authors[${i}][department]"></div><div class="field"><label>Institution *</label><input name="authors[${i}][institution]" required></div><div class="field"><label>City</label><input name="authors[${i}][city]"></div><div class="field"><label>State/Province</label><input name="authors[${i}][state]"></div><div class="field"><label>Country *</label><input name="authors[${i}][country]" required></div><div class="field full"><label>Author Contributions</label><select name="authors[${i}][contribution][]" multiple size="4">${C.map(x=>`<option value="${x}">${x}</option>`).join('')}</select></div></div>`;document.getElementById('authors').appendChild(d)}
function addAff(){let i=af++,d=document.createElement('div');d.className='aff';d.innerHTML=`<h3>Affiliation ${i+1}</h3><div class="grid"><div class="field"><label>Department</label><input name="affiliations[${i}][department]"></div><div class="field"><label>Institution *</label><input name="affiliations[${i}][institution]" required></div><div class="field"><label>City</label><input name="affiliations[${i}][city]"></div><div class="field"><label>State/Province</label><input name="affiliations[${i}][state]"></div><div class="field"><label>Country *</label><input name="affiliations[${i}][country]" required></div></div>`;document.getElementById('affs').appendChild(d)}
function addReviewer(t){let i=rc++,d=document.createElement('div');d.className='reviewer';d.innerHTML=`<h3>${t==='suggested'?'Suggested':'Excluded'} Reviewer</h3><input type="hidden" name="${t}_reviewers[${i}][type]" value="${t}"><div class="grid"><div class="field"><label>Full Name</label><input name="${t}_reviewers[${i}][full_name]"></div><div class="field"><label>Email</label><input type="email" name="${t}_reviewers[${i}][email]"></div><div class="field"><label>Institution</label><input name="${t}_reviewers[${i}][institution]"></div><div class="field"><label>Country</label><input name="${t}_reviewers[${i}][country]"></div><div class="field"><label>ORCID</label><input name="${t}_reviewers[${i}][orcid]"></div><div class="field"><label>Expertise</label><input name="${t}_reviewers[${i}][expertise]"></div>${t==='excluded'?`<div class="field full"><label>Reason</label><textarea name="${t}_reviewers[${i}][reason]"></textarea></div>`:''}</div>`;document.getElementById('reviewers').appendChild(d)}
addAuthor();addAff();
</script></body></html>
