CREATE TABLE users(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(180) NOT NULL,
 email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
 role ENUM('admin','editor_in_chief','editor','reviewer','author','production') NOT NULL,
 affiliation VARCHAR(255), phone VARCHAR(50), orcid VARCHAR(100), expertise TEXT,
 active TINYINT(1) DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE manuscripts(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, manuscript_no VARCHAR(40) UNIQUE NOT NULL,
 title VARCHAR(500) NOT NULL, abstract MEDIUMTEXT, keywords VARCHAR(1000), article_type VARCHAR(100),
 corresponding_author_id INT UNSIGNED, assigned_editor_id INT UNSIGNED,
 status ENUM('SUBMITTED','TECHNICAL_CHECK','PLAGIARISM_CHECK','EDITORIAL_SCREENING','ASSIGNED_TO_EDITOR','REVIEWER_INVITATION','UNDER_REVIEW','REVISION_REQUIRED','REVISED_SUBMISSION','SECOND_REVIEW','ACCEPTED','PRODUCTION','PROOF_SENT','PROOF_APPROVED','PUBLISHED','REJECTED','WITHDRAWN') DEFAULT 'SUBMITTED',
 version_no INT DEFAULT 1, similarity_percent DECIMAL(5,2), plagiarism_notes TEXT, ethics_statement TEXT,
 conflict_statement TEXT, funding_statement TEXT, manuscript_file VARCHAR(500), final_file VARCHAR(500),
 submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 accepted_at DATETIME, published_at DATETIME,
 FOREIGN KEY(corresponding_author_id) REFERENCES users(id) ON DELETE SET NULL,
 FOREIGN KEY(assigned_editor_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE manuscript_authors(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, manuscript_id INT UNSIGNED NOT NULL,
 author_user_id INT UNSIGNED, author_name VARCHAR(180) NOT NULL, affiliation VARCHAR(255), email VARCHAR(190),
 author_order INT DEFAULT 1, FOREIGN KEY(manuscript_id) REFERENCES manuscripts(id) ON DELETE CASCADE,
 FOREIGN KEY(author_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE reviews(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, manuscript_id INT UNSIGNED NOT NULL, reviewer_id INT UNSIGNED NOT NULL,
 status ENUM('INVITED','ACCEPTED','DECLINED','SUBMITTED') DEFAULT 'INVITED',
 comments_to_editor TEXT, comments_to_author TEXT,
 recommendation ENUM('ACCEPT','MINOR_REVISION','MAJOR_REVISION','REJECT'),
 invited_at DATETIME DEFAULT CURRENT_TIMESTAMP, accepted_at DATETIME, due_at DATETIME, submitted_at DATETIME,
 FOREIGN KEY(manuscript_id) REFERENCES manuscripts(id) ON DELETE CASCADE,
 FOREIGN KEY(reviewer_id) REFERENCES users(id) ON DELETE CASCADE,
 UNIQUE KEY uq_review(manuscript_id,reviewer_id)
) ENGINE=InnoDB;
CREATE TABLE manuscript_versions(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, manuscript_id INT UNSIGNED NOT NULL, version_no INT NOT NULL,
 file_path VARCHAR(500) NOT NULL, author_response TEXT, uploaded_by INT UNSIGNED, created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(manuscript_id) REFERENCES manuscripts(id) ON DELETE CASCADE,
 FOREIGN KEY(uploaded_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE decisions(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, manuscript_id INT UNSIGNED NOT NULL, user_id INT UNSIGNED,
 decision ENUM('SEND_FOR_REVIEW','TECHNICAL_CORRECTION','ACCEPT','MINOR_REVISION','MAJOR_REVISION','REJECT','WITHDRAW') NOT NULL,
 notes TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(manuscript_id) REFERENCES manuscripts(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE production(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, manuscript_id INT UNSIGNED UNIQUE NOT NULL,
 copyediting_status ENUM('PENDING','IN_PROGRESS','COMPLETED') DEFAULT 'PENDING',
 typesetting_status ENUM('PENDING','IN_PROGRESS','COMPLETED') DEFAULT 'PENDING',
 proof_status ENUM('PENDING','SENT','APPROVED') DEFAULT 'PENDING',
 volume VARCHAR(30), issue VARCHAR(30), year SMALLINT, pages VARCHAR(50), doi VARCHAR(255), final_pdf VARCHAR(500), notes TEXT,
 FOREIGN KEY(manuscript_id) REFERENCES manuscripts(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE issues(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, volume VARCHAR(30) NOT NULL, issue VARCHAR(30) NOT NULL,
 issue_title VARCHAR(255), year SMALLINT NOT NULL, publication_date DATE,
 UNIQUE KEY uq_issue(volume,issue,year)
) ENGINE=InnoDB;
CREATE TABLE audit_log(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED, manuscript_id INT UNSIGNED,
 action VARCHAR(120) NOT NULL, details TEXT, ip_address VARCHAR(45), created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(manuscript_id) REFERENCES manuscripts(id) ON DELETE SET NULL
) ENGINE=InnoDB;
